<?php

namespace NachoBrito\BOECrawlerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaryRepository extends EntityRepository
{
}
